import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import AppTheme from "@/theme/AppTheme";
import {NextIntlClientProvider} from 'next-intl';
import { Public_Sans, Battambang } from "next/font/google";
import { cookies } from "next/headers";
import "nprogress/nprogress.css";

const public_sans = Public_Sans({
    subsets: ["latin"],
    display: "swap",
});

const battambang = Battambang({
    subsets: ["khmer"],
    weight: ["400", "700"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = await cookies();
    const locale = cookieStore.get("locale")?.value || "kh";
    const fontClass = locale === "kh" ? battambang.className : public_sans.className;
    return (
        <html
            lang={locale}
            className={fontClass}
        >
            <body>
                <AppRouterCacheProvider>
                    <AppTheme locale={locale}>
                        <NextIntlClientProvider>
                            {children}
                        </NextIntlClientProvider>
                    </AppTheme>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
